name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Downloading SFML
      run: |
        wget -O SFML.zip https://www.sfml-dev.org/files/SFML-2.5.1-sources.zip
        unzip SFML.zip SFML
        ls

    - name: building
      run: |
        mkdir build
        cd build
        cmake ..
        make
        ls

    - run: ls
