name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - run: ls

    - name: building
      uses: nicledomaS/cmake_build_action@v1.4

    - run: ls
